// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://janvznwulosbrsknishq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphbnZ6bnd1bG9zYnJza25pc2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTE4ODksImV4cCI6MjA2MTY4Nzg4OX0.Jxv9RZ9MZsxMcbjL2RtFenATdv1_J_8dyBl-ZGO68sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);